version: '2'
services:
  spark-master:
    image: qulo/rancher-spark
    ports:
      - "8080:8080"
    environment:
      SPARK_CONF_DIR: /conf
    command:
    - master
    - spark-master
  spark-worker:
    image: qulo/rancher-spark
    environment:
      SPARK_CONF_DIR: /conf
    links:
    - spark-master
    command:
    - worker
    - spark://spark-master:7077